CREATE TABLE OPERADORA (
O_CODIGO BIGINT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTE (
C_CODIGO BIGINT NOT NULL PRIMARY KEY,
DATA_NASC DATE NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPF CHAR(11) NOT NULL,
EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE TELEFONE (
T_CODIGO BIGINT NOT NULL PRIMARY KEY,
TIPO VARCHAR(50) NOT NULL,
NUMERO CHAR(10) NOT NULL,
C_CODIGO BIGINT NOT NULL,
O_CODIGO BIGINT NOT NULL,
FOREIGN KEY(C_CODIGO) REFERENCES CLIENTE (C_CODIGO),
FOREIGN KEY(O_CODIGO) REFERENCES OPERADORA (O_CODIGO)
);
